# Generated by Django 3.1.dev20200122124522 on 2020-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
